#Updated dynamically from UI
#Wed Mar 25 06:26:04 EDT 2026
Authentication_Type=OAUTH
Authorization=Basic OWExYzkxOTgtMjZmZi0zZWNmLWFlNjMtNWYzNDMxZTY4MzkzOlNaZjNGMnU4bkhncWI5NnAxMm81MjF6MG5WcVRtYw\=\=
CLIENT_ID=9a1c9198-26ff-3ecf-ae63-5f3431e68393
CLIENT_SECRET=SZf3F2u8nHgqb96p12o521z0nVqTmc
GRANT_TYPE=client_credentials
TOKEN_URL=https\://oauthasservices-gsv2nn12cp.ca1.hana.ondemand.com/oauth2/api/v1/token
